export const CONSTANTS = {
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  CATEGORY_PROVIDER: 'CATEGORY_PROVIDER',
  PRODUCT_PROVIDER: 'PRODUCT_PROVIDER',
  ORDER_PROVIDER: 'ORDER_PROVIDER',
  USER_PROVIDER: 'USER_PROVIDER',
};
